version: '3'
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ${APPLICATION}:/var/www
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        links:
            - php-fpm
        networks:
            - code-network

    php-fpm:
        container_name: php-fpm
        restart: 'always'
        build:
            context: ./php
            dockerfile: Dockerfile
        expose:
            - "9000"    
        volumes:
            - ${APPLICATION}:/var/www
        networks:
            - code-network

    composer:
        container_name: composer
        build:
            context: ./composer
            dockerfile: Dockerfile
        volumes:
            - ${APPLICATION}/blog:/app
        command: ["composer", "install"]

networks:
    code-network:
        driver: bridge
